name: swarm
channels:
  - conda-forge
dependencies:
  - gdal
  - pip
  # - pip:
  #     - watermark
  #     - viresclient
  #     - python-dotenv
  #     - hdf5storage # for chaosmagpy
  #     - netCDF4
  #     - git+https://github.com/treebeardtech/nbmake.git@err-view
  #     - pytest-xdist
  #     - chaosmagpy
  #     - python_dateutil
  #     - swarmpyfac

    