#!/usr/bin/env bash
set -x -euo pipefail

pip install chaosmagpy

wget --no-verbose https://github.com/ESA-VirES/MagneticModel/archive/master.zip -O MagneticModel.zip
unzip MagneticModel.zip
mv MagneticModel-master MagneticModel

conda build MagneticModel/libcdf
conda build MagneticModel/qdipole
conda install --quiet --yes --use-local qdipole cdf

pip install python_dateutil
pip install --no-deps spacepy