on:
  push:
    branches:
      - master
      - staging
  pull_request:
    branches:
      - master
      - staging
  schedule:
    - cron: "0 0 * * 0" # weekly
jobs:
  run:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    name: Test
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - uses: actions/checkout@v2
        with:
          repository: "ESA-VirES/MagneticModel"
          ref: 9eee7382a9f896a42f5032fdb38e650eba9861fa
          path: MagneticModel
      - run: |
            bash -c 'cd MagneticModel/libcdf && make build && sudo make install'
      - run: |
            bash -c 'cd MagneticModel/qdipole && ./configure && make build && sudo make install'
      - run: pip install scipy
      - run: pip install MagneticModel/eoxmagmod/
      - uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: 3.8
          activate-environment: swarm
          channel-priority: true
          environment-file: environment.yml
          auto-activate-base: false
      # - name: Setup tmate session
      #   uses: mxschmitt/action-tmate@v3
      - run: pytest --nbmake -n=auto notebooks