on:
  push:
    branches:
      - master
      - staging
  pull_request:
    branches:
      - master
      - staging
  schedule:
    - cron: "0 0 * * 0" # weekly
jobs:
  run:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: 3.8
          activate-environment: swarm
          channel-priority: true
          environment-file: environment.yml
          auto-activate-base: false
      - run: conda info
      # - name: Setup tmate session
      #   uses: mxschmitt/action-tmate@v3
      #   continue-on-error: true
      # - name: Build environment
      #   run: |
      #     set -x -euo pipefail

      #     pip install chaosmagpy

      #     wget --no-verbose https://github.com/ESA-VirES/MagneticModel/archive/master.zip -O MagneticModel.zip
      #     unzip MagneticModel.zip
      #     mv MagneticModel-master MagneticModel

      #     conda build MagneticModel/libcdf
      #     conda build MagneticModel/qdipole
      #     conda install --quiet --yes --use-local qdipole cdf

      #     pip install python_dateutil
      #     pip install --no-deps spacepy

      #     pip install MagneticModel/eoxmagmod
      #     pip install swarmpyfac
      # - run: pytest --nbmake -n=auto notebooks