on:
  push:
    branches:
      - master
      - staging
  pull_request:
    branches:
      - master
      - staging
  schedule:
    - cron: "0 0 * * 0" # weekly
jobs:
  run:
    runs-on: ubuntu-latest
    name: Run treebeard
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: goanpeca/setup-miniconda@v2.0.1
        with:
          activate-environment: swarm
          environment-file: environment.yml
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        with:
          sudo: false
      - name: Build environment
        run: |
          set -x -euo pipefail

          pip install chaosmagpy

          wget --no-verbose https://github.com/ESA-VirES/MagneticModel/archive/master.zip -O MagneticModel.zip
          unzip MagneticModel.zip
          mv MagneticModel-master MagneticModel

          conda build MagneticModel/libcdf
          conda build MagneticModel/qdipole
          conda install --quiet --yes --use-local qdipole cdf

          pip install python_dateutil
          pip install --no-deps spacepy

          pip install MagneticModel/eoxmagmod
          pip install swarmpyfac
      - run: pytest --nbmake -n=auto notebooks